const BAD_REQUEST_ERROR_CODE = 400;
const NOT_FOUND_ERROR_CODE = 404;
const INTERNAL_SERVER_ERROR = 500;
const SUCCESS = 200;
const CREATED = 201;
const UNAUTHORIZED = 401;
const CONFLICT = 409;
const FORBIDDEN = 403;

module.exports = {
  BAD_REQUEST_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  INTERNAL_SERVER_ERROR,
  SUCCESS,
  CREATED,
  UNAUTHORIZED,
  CONFLICT,
  FORBIDDEN
};
